<?php

return [
    'full_time' => [
        [
            'title' => 'Corporate Strategy Associate',
            'company' => 'Starforge Robotics',
            'location' => 'San Francisco, CA · Hybrid',
            'description' => 'Own go-to-market strategy sprints alongside product and revenue. Partner with exec staff to scope new verticals, model growth, and architect launch playbooks.',
            'apply_url' => 'https://example.com/jobs/starforge-strategy-associate',
            'logo' => 'https://logo.clearbit.com/openai.com?size=80',
        ],
        [
            'title' => 'Product Marketing Manager',
            'company' => 'Aurora BioLabs',
            'location' => 'Boston, MA · Onsite',
            'description' => 'Translate R&D breakthroughs into enterprise messaging. Build repeatable launch motions and lead cross-functional storytelling for AI-enabled diagnostics.',
            'apply_url' => 'https://example.com/jobs/aurora-pmm',
            'logo' => 'https://logo.clearbit.com/slack.com?size=80',
        ],
        [
            'title' => 'Venture Operations Lead',
            'company' => 'Northwind Capital',
            'location' => 'New York, NY · In office',
            'description' => 'Scale the investor network, diligence pipeline, and portfolio ops engine. Lead KPI instrumentation, create investor narratives, and coach founders.',
            'apply_url' => 'https://example.com/jobs/northwind-ops-lead',
            'logo' => 'https://logo.clearbit.com/stripe.com?size=80',
        ],
        [
            'title' => 'Global Partnerships Manager',
            'company' => 'Helios Mobility',
            'location' => 'Austin, TX · Hybrid',
            'description' => 'Architect expansion partnerships with enterprise fleets and municipal partners. Negotiate multi-year agreements and build partner enablement playbooks.',
            'apply_url' => 'https://example.com/jobs/helios-partnerships',
            'logo' => 'https://logo.clearbit.com/uber.com?size=80',
        ],
        [
            'title' => 'Revenue Strategy Consultant',
            'company' => 'Brightpath Analytics',
            'location' => 'Chicago, IL · Remote friendly',
            'description' => 'Lead pricing and monetisation projects for Fortune 500 innovation teams. Stand up experiment frameworks and mentor analysts through delivery.',
            'apply_url' => 'https://example.com/jobs/brightpath-revenue',
            'logo' => 'https://logo.clearbit.com/atlassian.com?size=80',
        ],
        [
            'title' => 'Chief of Staff',
            'company' => 'Veridian Health',
            'location' => 'Seattle, WA · Hybrid',
            'description' => 'Partner with the CEO to align strategic initiatives, manage operating cadence, and incubate new programs across clinical, product, and GTM.',
            'apply_url' => 'https://example.com/jobs/veridian-chief-of-staff',
            'logo' => 'https://logo.clearbit.com/roche.com?size=80',
        ],
    ],
    'internships' => [
        [
            'title' => 'Strategy & Ops Intern',
            'company' => 'Nova Labs',
            'location' => 'Remote · North America',
            'description' => 'Partner with the COO to evaluate market expansion bets, build Monte Carlo models, and ship the go-to-market dashboard for the leadership team.',
            'apply_url' => 'https://example.com/internships/nova-strategy-ops',
            'logo' => 'https://logo.clearbit.com/notion.so?size=80',
            'duration' => '10-12 weeks · Summer 2025',
        ],
        [
            'title' => 'Product Marketing MBA Intern',
            'company' => 'LumenAI',
            'location' => 'San Jose, CA · Hybrid',
            'description' => 'Craft launch narratives for AI copilots, develop activation experiments with growth, and deliver insights to the GTM leadership pod.',
            'apply_url' => 'https://example.com/internships/lumenai-pmm',
            'logo' => 'https://logo.clearbit.com/nvidia.com?size=80',
            'duration' => '10 weeks · Summer 2025',
        ],
        [
            'title' => 'Corporate Development Intern',
            'company' => 'Helios Mobility',
            'location' => 'Austin, TX · Hybrid',
            'description' => 'Support live buy-side diligence, build integration playbooks, and deliver board-ready materials on fleet electrification initiatives.',
            'apply_url' => 'https://example.com/internships/helios-corp-dev',
            'logo' => 'https://logo.clearbit.com/tesla.com?size=80',
            'duration' => '12 weeks · Summer 2025',
        ],
        [
            'title' => 'Venture Capital MBA Intern',
            'company' => 'Northwind Capital',
            'location' => 'New York, NY · In office',
            'description' => 'Source frontier fintech and climate deals, own diligence streams, and architect market maps for the partnership.',
            'apply_url' => 'https://example.com/internships/northwind-vc',
            'logo' => 'https://logo.clearbit.com/sequoiacap.com?size=80',
            'duration' => '8-10 weeks · Summer 2025',
        ],
    ],
];
